### PR TITLE
Updated readme to reflect new sql header in tests

### PR DESCRIPTION
**Pull request by artygus**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@artygus Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/trilogy&pullRequestId=4)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/trilogy&pullRequestId=4) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@artygus Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/trilogy&pullRequestId=4)!

**Comment by artygus** [comment]
https://github.com/pivotal/trilogy/commit/5240afee50da3891cbd3b54ac02b79e1fdf7aa79

**Comment by jhvhs** [comment]
Hi @artygus,

Thank you for submitting the pull request.
Unfortunately, I only saw it after I made the change.

**Pull request closed without merging**
